export default {
    SUBMIT_REGISTER: 'SUBMIT_REGISTER', // 注册
    SUBMIT_LOGIN: 'SUBMIT_LOGIN', // 登录
    INITDATA_SELF: 'INITDATA_SELF', // 初始化用户个人资料
    MODIFYDATA_SELF: 'MODIFYDATA_SELF', // 修改用户个人资料
    MODIFYDATA_PASS: 'MODIFYDATA_PASS', // 修改密码
    INITDATA_MYFILE: 'INITDATA_MYFILE', // 初始化我的文档
    INITMENUS_MYFILE: 'INITMENUS_MYFILE', // 初始化我的文档菜单
    PASTEDATA_MYFILE: 'PASTEDATA_MYFILE', // 粘贴我的文档文件
    RENAMEDATA_MYFILE: 'RENAMEDATA_MYFILE', // 重命名我的文档文件
    TODATA_MYFILE: 'TODATA_MYFILE', // 文件栏跳转我的文档文件
    DELETEDATA_MYFILE: 'DELETEDATA_MYFILE', //删除我的文档文件
    SHEARDATA_MYFILE: 'SHEARDATA_MYFILE', // 剪切我的文档文件
    CREATEDATA_MYFILE: 'CREATEDATA_MYFILE', // 新建文件夹
    UPLODADATA_MYFILE: 'UPLODADATA_MYFILE', // 上传文件
    FINDDATA_MYFILE: 'FINDDATA_MYFILE', // 搜索文件
    FINDDATA_FAVOUR: 'FINDDATA_FAVOUR', // 搜索文件收藏夹
    FINDDATA_FILE: 'FINDDATA_FILE', // 搜索文件文档
    ADDFAVOURDATA_MYFILE: 'ADDDATA_MYFILE', // 收藏文件
    CENCELFAVOURDATA_FAVOUR: 'CENCELFAVOURDATA_FAVOUR', // 取消收藏
    BACKDATA_MYFILE: 'BACKDATA_MYFILE', // 后退文件
    FRONTDATA_MYFILE: 'FRONTDATA_MYFILE', // 前进文件
    INITDATA_DUSTBIN: 'INITDATA_DUSTBIN', // 初始化垃圾箱
    DELETEDATA_DUSTBIN: 'DELETEDATA_DUSTBIN', // 垃圾箱彻底删除
    REDUCTIONDATA_DUSTBIN: 'REDUCTIONDATA_DUSTBIN', // 垃圾箱还原
    FINDDATA_DUSTBIN: 'FINDDATA_DUSTBIN', // 搜索文件垃圾箱
    INITDATA_FAVOURITE: 'INITDATA_FAVOURITE', // 初始化收藏夹
    INITDATA_FILE: 'INITDATA_FILE', // 初始化文件数据
}