const icon = {
    user_icon_copy: require('./icon/user_icon_copy.png'),
    tick: require('./icon/tick.png'),
    lock_icon_copy: require('./icon/lock_icon_copy.png'),
    key: require('./icon/key.png'),
    favorites: require('./icon/favorites.png'),
    favorites2: require('./icon/favorites2.png'),
    file1: require('./icon/file1.png'),
    file3: require('./icon/file3.png'),
    file4: require('./icon/file4.png'),
    photo: require('./icon/photo.png'),
    music: require('./icon/music.png'),
    video: require('./icon/video.png'),
    package: require('./icon/package.png'),
    compiler: require('./icon/compiler.png'),
    house: require('./icon/house.png'),
    time: require('./icon/time.png'),
    link: require('./icon/link.png'),
    dustbin: require('./icon/dustbin.png'),
    refresh: require('./icon/refresh.png'),
    openFile: require('./icon/openFile.png'),
    copy: require('./icon/copy.png'),
    favorited: require('./icon/favorited.png'),
    find: require('./icon/find.png'),
    overlapping: require('./icon/overlapping.png'),
    setting: require('./icon/setting.png'),
    self: require('./icon/self.png'),
    watch: require('./icon/watch.png'),
    exclamatory: require('./icon/exclamatory.png'),
    news: require('./icon/news.png'),
    location: require('./icon/location.png'),
    true: require('./icon/true.png'),
    attribute: require('./icon/attribute.png'),
    paste: require('./icon/paste.png'),
    sort: require('./icon/sort.png'),
    shear: require('./icon/shear.png'),
    rename: require('./icon/rename.png'),
    download: require('./icon/download.png'),
    open: require('./icon/open.png'),
    word: require('./icon/word.png'),
    ppt: require('./icon/ppt.png'),
    excel: require('./icon/excel.png'),
    pdf: require('./icon/PDF.png'),
    reduction: require('./icon/reduction.png'),
};

const common= {
    logo: require('./common/logo.png'),
    logo1: require('./common/logo1.png'),
    house: require('./common/house.png'),
    favorites: require('./common/favorites.png'),
    arrow: require('./common/arrow.png'),
    arrow2: require('./common/arrow2.png'),
    find: require('./common/find.png'),
    file: require('./common/file.png'),
    flag: require('./common/flag.png'),
    self: require('./common/self.jpg'),
    slide1: require('./common/slider_img1.jpg'),
    slide2: require('./common/slider_img2.jpg'),
    slide3: require('./common/slider_img3.jpg'),
    slide4: require('./common/slider_img4.jpg'),
    slide5: require('./common/slider_img5.jpg'),
    logoText: require('./common/logo-text.png'),
    logoIcon: require('./common/logo-icon.png'),
    news: require('./common/news.png'),
    adminPhoto: require('./common/1.jpg'),
    mainImg1: require('./common/main_img1.jpg'),
    mainImg2: require('./common/main_img2.jpg'),
    mainImg3: require('./common/main_img3.jpg'),
    mainImg4: require('./common/main_img4.jpg'),
    mainImg5: require('./common/main_img5.jpg'),
    mainImg6: require('./common/main_img6.jpg'),
    mainImg7: require('./common/main_img7.jpg'),
    mainImg8: require('./common/main_img8.jpg'),
    mainImg9: require('./common/main_img9.jpg'),
    mainImg10: require('./common/main_img10.jpg'),
    userImg1: require('./common/user_img1.jpg'),
    userImg2: require('./common/user_img2.jpg'),
    userImg3: require('./common/user_img3.jpg'),
    userImg4: require('./common/user_img4.jpg'),
    userImg5: require('./common/user_img5.jpg'),
    headImg1: require('./common/head_img1.jpeg'),
    headImg2: require('./common/head_img2.jpeg'),
    headImg3: require('./common/head_img3.jpeg'),
    headImg4: require('./common/head_img4.jpeg'),
    headImg5: require('./common/head_img5.jpeg'),
    live1: require('./common/live1.webp'),
    male: require('./common/male.png'),
    female: require('./common/female.png'),
    button: require('./common/button.png'),
    nofile: require('./common/nofile.jpg'),
}

export {
    icon,
    common
};